// POSITIONS DATA
// -----------------------------------------------------------------
// Add your positions here. Each entry needs:
//   text      -> the position name/description (required)
//   tier      -> exactly one of: "Easy", "Medium", "Hard", "Extreme" (required)
//   imagePath -> filename of an image in the /images folder, or "" if none (optional)
//
// Imported from Positions.xlsx (425 entries) with images from the
// "Crimson Violet" set. Difficulty mapping: 1=Easy, 2=Medium, 3=Hard, 4=Extreme.
// -----------------------------------------------------------------

const POSITIONS = [
  { text: "Abyss", tier: "Medium", imagePath: "images/Abyss.png" },
  { text: "Accordion", tier: "Easy", imagePath: "images/Accordion.png" },
  { text: "Acrobat", tier: "Easy", imagePath: "images/Acrobat.png" },
  { text: "Adventurer", tier: "Easy", imagePath: "images/Adventurer.png" },
  { text: "Air Rider", tier: "Hard", imagePath: "images/Air Rider.png" },
  { text: "Airplane", tier: "Hard", imagePath: "images/Airplane.png" },
  { text: "Alley", tier: "Medium", imagePath: "images/Alley.png" },
  { text: "Amateur", tier: "Medium", imagePath: "images/Amateur.png" },
  { text: "Amazing Meeting", tier: "Medium", imagePath: "images/Amazing Meeting.png" },
  { text: "Amazon", tier: "Medium", imagePath: "images/Amazon.png" },
  { text: "American Pie", tier: "Medium", imagePath: "images/American Pie.png" },
  { text: "Amphibian", tier: "Easy", imagePath: "images/Amphibian.png" },
  { text: "Angry Pirate", tier: "Easy", imagePath: "images/Angry Pirate.png" },
  { text: "Anna", tier: "Easy", imagePath: "images/Anna.png" },
  { text: "Anvil", tier: "Easy", imagePath: "images/Anvil.png" },
  { text: "Aphrodite", tier: "Medium", imagePath: "images/Aphrodite.png" },
  { text: "Apologies", tier: "Easy", imagePath: "images/Apologies.png" },
  { text: "Appetite", tier: "Easy", imagePath: "images/Appetite.png" },
  { text: "Aquarius", tier: "Medium", imagePath: "images/Aquarius.png" },
  { text: "Aries", tier: "Medium", imagePath: "images/Aries.png" },
  { text: "Asteroid", tier: "Hard", imagePath: "images/Asteroid.png" },
  { text: "Astrologer", tier: "Extreme", imagePath: "images/Astrologer.png" },
  { text: "Awesome Idea", tier: "Medium", imagePath: "images/Awesome Idea.png" },
  { text: "Backdoor", tier: "Medium", imagePath: "images/Backdoor.png" },
  { text: "Backrest", tier: "Medium", imagePath: "images/Backrest.png" },
  { text: "Backshot", tier: "Easy", imagePath: "images/Backshot.png" },
  { text: "Backstroke", tier: "Easy", imagePath: "images/Backstroke.png" },
  { text: "Backwards Cowgirl", tier: "Easy", imagePath: "images/Backwards Cowgirl.png" },
  { text: "Banana Split", tier: "Hard", imagePath: "images/Banana Split.png" },
  { text: "Barbell", tier: "Hard", imagePath: "images/Barbell.png" },
  { text: "Barberry", tier: "Medium", imagePath: "images/Barberry.png" },
  { text: "Barbie", tier: "Easy", imagePath: "images/Barbie.png" },
  { text: "Basket", tier: "Medium", imagePath: "images/Basket.png" },
  { text: "Batman", tier: "Easy", imagePath: "images/Batman.png" },
  { text: "Bench", tier: "Hard", imagePath: "images/Bench.png" },
  { text: "Bent Cowgirl", tier: "Medium", imagePath: "images/Bent Cowgirl.png" },
  { text: "Biethday Party", tier: "Extreme", imagePath: "images/Biethday Party.png" },
  { text: "Binding", tier: "Easy", imagePath: "images/Binding.png" },
  { text: "Bizzet", tier: "Easy", imagePath: "images/Bizzet.png" },
  { text: "Blade", tier: "Easy", imagePath: "images/Blade.png" },
  { text: "Boat", tier: "Easy", imagePath: "images/Boat.png" },
  { text: "Book", tier: "Easy", imagePath: "images/Book.png" },
  { text: "Bow 2", tier: "Medium", imagePath: "images/Bow 2.png" },
  { text: "Bow", tier: "Easy", imagePath: "images/Bow.png" },
  { text: "Bowstring", tier: "Easy", imagePath: "images/Bowstring.png" },
  { text: "Breeze", tier: "Easy", imagePath: "images/Breeze.png" },
  { text: "Bridge", tier: "Medium", imagePath: "images/Bridge.png" },
  { text: "Bud", tier: "Easy", imagePath: "images/Bud.png" },
  { text: "Bulldog", tier: "Medium", imagePath: "images/Bulldog.png" },
  { text: "Bullfighter", tier: "Easy", imagePath: "images/Bullfighter.png" },
  { text: "Bung", tier: "Easy", imagePath: "images/Bung.png" },
  { text: "Butter Churner", tier: "Hard", imagePath: "images/Butter Churner.png" },
  { text: "Butterfly", tier: "Easy", imagePath: "images/Butterfly.png" },
  { text: "Buttler", tier: "Easy", imagePath: "images/Buttler.png" },
  { text: "Bycycle", tier: "Medium", imagePath: "images/Bycycle.png" },
  { text: "Canafian", tier: "Hard", imagePath: "images/Canafian.png" },
  { text: "Cancer", tier: "Medium", imagePath: "images/Cancer.png" },
  { text: "Candle", tier: "Medium", imagePath: "images/Candle.png" },
  { text: "Capricorn", tier: "Medium", imagePath: "images/Capricorn.png" },
  { text: "Captain", tier: "Easy", imagePath: "images/Captain.png" },
  { text: "Captivity", tier: "Hard", imagePath: "images/Captivity.png" },
  { text: "Car Mechanic", tier: "Easy", imagePath: "images/Car Mechanic.png" },
  { text: "Caramel", tier: "Medium", imagePath: "images/Caramel.png" },
  { text: "Case", tier: "Medium", imagePath: "images/Case.png" },
  { text: "Cat", tier: "Easy", imagePath: "images/Cat.png" },
  { text: "Catapult", tier: "Easy", imagePath: "images/Catapult.png" },
  { text: "Catch", tier: "Hard", imagePath: "images/Catch.png" },
  { text: "Cave", tier: "Hard", imagePath: "images/Cave.png" },
  { text: "Chair", tier: "Medium", imagePath: "images/Chair.png" },
  { text: "Chairman", tier: "Hard", imagePath: "images/Chairman.png" },
  { text: "Chef", tier: "Easy", imagePath: "images/Chef.png" },
  { text: "Chibi", tier: "Easy", imagePath: "images/Chibi.png" },
  { text: "Chilli Dog", tier: "Hard", imagePath: "images/Chilli Dog.png" },
  { text: "Chinese Art", tier: "Hard", imagePath: "images/Chinese Art.png" },
  { text: "Circle", tier: "Easy", imagePath: "images/Circle.png" },
  { text: "Clapper", tier: "Hard", imagePath: "images/Clapper.png" },
  { text: "Cleopatra", tier: "Easy", imagePath: "images/Cleopatra.png" },
  { text: "Clip Position(1)", tier: "Hard", imagePath: "images/Clip Position(1).png" },
  { text: "Clip", tier: "Medium", imagePath: "images/Clip.png" },
  { text: "Close Breathing", tier: "Easy", imagePath: "images/Close Breathing.png" },
  { text: "Cobra", tier: "Medium", imagePath: "images/Cobra.png" },
  { text: "Coffee Table", tier: "Hard", imagePath: "images/Coffee Table.png" },
  { text: "Column", tier: "Hard", imagePath: "images/Column.png" },
  { text: "Compliment", tier: "Easy", imagePath: "images/Compliment.png" },
  { text: "Concubine", tier: "Medium", imagePath: "images/Concubine.png" },
  { text: "Conqueror", tier: "Medium", imagePath: "images/Conqueror.png" },
  { text: "Corkscrew", tier: "Hard", imagePath: "images/Corkscrew.png" },
  { text: "Courtesan", tier: "Hard", imagePath: "images/Courtesan.png" },
  { text: "Cowboy", tier: "Hard", imagePath: "images/Cowboy.png" },
  { text: "Cowgirl On The Chair", tier: "Medium", imagePath: "images/Cowgirl On The Chair.png" },
  { text: "Cowgirl On The Table", tier: "Hard", imagePath: "images/Cowgirl On The Table.png" },
  { text: "Cowgirl", tier: "Easy", imagePath: "images/Cowgirl.png" },
  { text: "Crab Position(1)", tier: "Medium", imagePath: "images/Crab Position(1).png" },
  { text: "Crab", tier: "Medium", imagePath: "images/Crab.png" },
  { text: "Cradle 2", tier: "Hard", imagePath: "images/Cradle 2.png" },
  { text: "Cradle", tier: "Hard", imagePath: "images/Cradle.png" },
  { text: "Crazy Train", tier: "Medium", imagePath: "images/Crazy Train.png" },
  { text: "Creme Brulee", tier: "Easy", imagePath: "images/Creme Brulee.png" },
  { text: "Croissant", tier: "Easy", imagePath: "images/Croissant.png" },
  { text: "Crouching Tiger", tier: "Medium", imagePath: "images/Crouching Tiger.png" },
  { text: "Crucifixion", tier: "Hard", imagePath: "images/Crucifixion.png" },
  { text: "Curiosity", tier: "Easy", imagePath: "images/Curiosity.png" },
  { text: "Deck Chair", tier: "Easy", imagePath: "images/Deck Chair.png" },
  { text: "Deep Stick", tier: "Medium", imagePath: "images/Deep Stick.png" },
  { text: "Deep Throat", tier: "Easy", imagePath: "images/Deep Throat.png" },
  { text: "Deja Vu", tier: "Easy", imagePath: "images/Deja Vu.png" },
  { text: "Delicacy", tier: "Medium", imagePath: "images/Delicacy.png" },
  { text: "Depth", tier: "Medium", imagePath: "images/Depth.png" },
  { text: "Descent", tier: "Medium", imagePath: "images/Descent.png" },
  { text: "Desert Island", tier: "Hard", imagePath: "images/Desert Island.png" },
  { text: "Diamond", tier: "Hard", imagePath: "images/Diamond.png" },
  { text: "Dirty Dancing", tier: "Hard", imagePath: "images/Dirty Dancing.png" },
  { text: "Dirty Sanchez", tier: "Easy", imagePath: "images/Dirty Sanchez.png" },
  { text: "Discharge", tier: "Medium", imagePath: "images/Discharge.png" },
  { text: "Disco", tier: "Hard", imagePath: "images/Disco.png" },
  { text: "Dive", tier: "Medium", imagePath: "images/Dive.png" },
  { text: "Doggy On The Edge 2", tier: "Medium", imagePath: "images/Doggy On The Edge 2.png" },
  { text: "Doggy On The Edge", tier: "Medium", imagePath: "images/Doggy On The Edge.png" },
  { text: "Doggy Style", tier: "Easy", imagePath: "images/Doggy Style.png" },
  { text: "Dolphin", tier: "Hard", imagePath: "images/Dolphin.png" },
  { text: "Donkey Punch", tier: "Hard", imagePath: "images/Donkey Punch.png" },
  { text: "Downstroke", tier: "Hard", imagePath: "images/Downstroke.png" },
  { text: "Downward Dog", tier: "Medium", imagePath: "images/Downward Dog.png" },
  { text: "Dragon", tier: "Easy", imagePath: "images/Dragon.png" },
  { text: "Dream", tier: "Medium", imagePath: "images/Dream.png" },
  { text: "Drum", tier: "Medium", imagePath: "images/Drum.png" },
  { text: "Dutch Oven", tier: "Hard", imagePath: "images/Dutch Oven.png" },
  { text: "Eagle", tier: "Easy", imagePath: "images/Eagle.png" },
  { text: "Ebony", tier: "Hard", imagePath: "images/Ebony.png" },
  { text: "Ecstasy", tier: "Medium", imagePath: "images/Ecstasy.png" },
  { text: "Eiffel Tower", tier: "Medium", imagePath: "images/Eiffel Tower.png" },
  { text: "Elephant", tier: "Hard", imagePath: "images/Elephant.png" },
  { text: "Emperor", tier: "Easy", imagePath: "images/Emperor.png" },
  { text: "Equilibrium", tier: "Medium", imagePath: "images/Equilibrium.png" },
  { text: "Eraser", tier: "Easy", imagePath: "images/Eraser.png" },
  { text: "Erotic Poster", tier: "Medium", imagePath: "images/Erotic Poster.png" },
  { text: "Exciting Game", tier: "Hard", imagePath: "images/Exciting Game.png" },
  { text: "Exotic Foreplay", tier: "Medium", imagePath: "images/Exotic Foreplay.png" },
  { text: "Face Sitting", tier: "Easy", imagePath: "images/Face Sitting.png" },
  { text: "Fairy", tier: "Medium", imagePath: "images/Fairy.png" },
  { text: "Fall", tier: "Easy", imagePath: "images/Fall.png" },
  { text: "Fan", tier: "Medium", imagePath: "images/Fan.png" },
  { text: "Fantastic Elevator", tier: "Extreme", imagePath: "images/Fantastic Elevator.png" },
  { text: "Fantasy", tier: "Medium", imagePath: "images/Fantasy.png" },
  { text: "Feeder", tier: "Medium", imagePath: "images/Feeder.png" },
  { text: "Fifth Element", tier: "Medium", imagePath: "images/Fifth Element.png" },
  { text: "Fire Hydrant", tier: "Easy", imagePath: "images/Fire Hydrant.png" },
  { text: "Fireman", tier: "Hard", imagePath: "images/Fireman.png" },
  { text: "Fireworks", tier: "Medium", imagePath: "images/Fireworks.png" },
  { text: "Flame", tier: "Hard", imagePath: "images/Flame.png" },
  { text: "Flash", tier: "Medium", imagePath: "images/Flash.png" },
  { text: "Flatiron", tier: "Easy", imagePath: "images/Flatiron.png" },
  { text: "Flying Squirrel", tier: "Extreme", imagePath: "images/Flying Squirrel.png" },
  { text: "Forbidden Fruit", tier: "Easy", imagePath: "images/Forbidden Fruit.png" },
  { text: "French Kiss", tier: "Easy", imagePath: "images/French Kiss.png" },
  { text: "Frog", tier: "Hard", imagePath: "images/Frog.png" },
  { text: "Froggy Style", tier: "Hard", imagePath: "images/Froggy Style.png" },
  { text: "Full Nelson", tier: "Medium", imagePath: "images/Full Nelson.png" },
  { text: "Funny Joke", tier: "Easy", imagePath: "images/Funny Joke.png" },
  { text: "Fusion", tier: "Hard", imagePath: "images/Fusion.png" },
  { text: "G-Force", tier: "Hard", imagePath: "images/G-Force.png" },
  { text: "Gemini", tier: "Medium", imagePath: "images/Gemini.png" },
  { text: "Ghetto", tier: "Easy", imagePath: "images/Ghetto.png" },
  { text: "Gimlet", tier: "Easy", imagePath: "images/Gimlet.png" },
  { text: "Glass", tier: "Easy", imagePath: "images/Glass.png" },
  { text: "Goddess", tier: "Easy", imagePath: "images/Goddess.png" },
  { text: "Gorge", tier: "Easy", imagePath: "images/Gorge.png" },
  { text: "Grasshopper", tier: "Medium", imagePath: "images/Grasshopper.png" },
  { text: "Guillotine", tier: "Medium", imagePath: "images/Guillotine.png" },
  { text: "Hard Worker", tier: "Hard", imagePath: "images/Hard Worker.png" },
  { text: "Harmony", tier: "Easy", imagePath: "images/Harmony.png" },
  { text: "Harness", tier: "Hard", imagePath: "images/Harness.png" },
  { text: "Harp", tier: "Medium", imagePath: "images/Harp.png" },
  { text: "Hero", tier: "Easy", imagePath: "images/Hero.png" },
  { text: "Holder", tier: "Medium", imagePath: "images/Holder.png" },
  { text: "Holiday", tier: "Medium", imagePath: "images/Holiday.png" },
  { text: "Honeymoon", tier: "Medium", imagePath: "images/Honeymoon.png" },
  { text: "Hook", tier: "Hard", imagePath: "images/Hook.png" },
  { text: "Horizon", tier: "Easy", imagePath: "images/Horizon.png" },
  { text: "Hostage", tier: "Medium", imagePath: "images/Hostage.png" },
  { text: "Hot Carl", tier: "Easy", imagePath: "images/Hot Carl.png" },
  { text: "Hot Lunch", tier: "Medium", imagePath: "images/Hot Lunch.png" },
  { text: "Hottest Lover", tier: "Medium", imagePath: "images/Hottest Lover.png" },
  { text: "Hucklebuck", tier: "Easy", imagePath: "images/Hucklebuck.png" },
  { text: "Hummingbird", tier: "Medium", imagePath: "images/Hummingbird.png" },
  { text: "Hunger", tier: "Easy", imagePath: "images/Hunger.png" },
  { text: "Ice Cream", tier: "Medium", imagePath: "images/Ice Cream.png" },
  { text: "Idyll", tier: "Easy", imagePath: "images/Idyll.png" },
  { text: "Indian Style", tier: "Medium", imagePath: "images/Indian Style.png" },
  { text: "Inquisitor", tier: "Easy", imagePath: "images/Inquisitor.png" },
  { text: "Insatiable Clitoris", tier: "Easy", imagePath: "images/Insatiable Clitoris.png" },
  { text: "Inseminator", tier: "Medium", imagePath: "images/Inseminator.png" },
  { text: "Inventive Sixty-Nine", tier: "Medium", imagePath: "images/Inventive Sixty-Nine.png" },
  { text: "Iris", tier: "Easy", imagePath: "images/Iris.png" },
  { text: "Iron Throne", tier: "Hard", imagePath: "images/Iron Throne.png" },
  { text: "Italian Chandelier", tier: "Hard", imagePath: "images/Italian Chandelier.png" },
  { text: "Jamaican Coctail", tier: "Hard", imagePath: "images/Jamaican Coctail.png" },
  { text: "Japan", tier: "Medium", imagePath: "images/Japan.png" },
  { text: "Jellyfish", tier: "Medium", imagePath: "images/Jellyfish.png" },
  { text: "Jockey", tier: "Easy", imagePath: "images/Jockey.png" },
  { text: "Joystick", tier: "Medium", imagePath: "images/Joystick.png" },
  { text: "Keeper", tier: "Easy", imagePath: "images/Keeper.png" },
  { text: "Khaleesi", tier: "Medium", imagePath: "images/Khaleesi.png" },
  { text: "Kinky Spider", tier: "Medium", imagePath: "images/Kinky Spider.png" },
  { text: "Kitchen", tier: "Medium", imagePath: "images/Kitchen.png" },
  { text: "Knot", tier: "Medium", imagePath: "images/Knot.png" },
  { text: "Ladies’ Man", tier: "Easy", imagePath: "images/Ladies’ Man.png" },
  { text: "Ladyboy", tier: "Hard", imagePath: "images/Ladyboy.png" },
  { text: "Lap Dance", tier: "Medium", imagePath: "images/Lap Dance.png" },
  { text: "Launch Pad", tier: "Medium", imagePath: "images/Launch Pad.png" },
  { text: "Lazy Evening", tier: "Medium", imagePath: "images/Lazy Evening.png" },
  { text: "Leapfrog", tier: "Hard", imagePath: "images/Leapfrog.png" },
  { text: "Legs In Their Air", tier: "Easy", imagePath: "images/Legs In Their Air.png" },
  { text: "Legs On Shoulders", tier: "Medium", imagePath: "images/Legs On Shoulders.png" },
  { text: "Leo", tier: "Medium", imagePath: "images/Leo.png" },
  { text: "Leopard", tier: "Medium", imagePath: "images/Leopard.png" },
  { text: "Liana", tier: "Hard", imagePath: "images/Liana.png" },
  { text: "Libido", tier: "Medium", imagePath: "images/Libido.png" },
  { text: "Libra", tier: "Extreme", imagePath: "images/Libra.png" },
  { text: "Licking Master", tier: "Easy", imagePath: "images/Licking Master.png" },
  { text: "Lizard", tier: "Medium", imagePath: "images/Lizard.png" },
  { text: "Lock", tier: "Medium", imagePath: "images/Lock.png" },
  { text: "Lotus Flower Postion", tier: "Easy", imagePath: "images/Lotus Flower Postion.png" },
  { text: "Louise", tier: "Medium", imagePath: "images/Louise.png" },
  { text: "Low Doggy", tier: "Medium", imagePath: "images/Low Doggy.png" },
  { text: "Low Start", tier: "Medium", imagePath: "images/Low Start.png" },
  { text: "Magic Carpet", tier: "Medium", imagePath: "images/Magic Carpet.png" },
  { text: "Magic Mountain", tier: "Easy", imagePath: "images/Magic Mountain.png" },
  { text: "Marmalade", tier: "Medium", imagePath: "images/Marmalade.png" },
  { text: "Marsh-Mallow", tier: "Easy", imagePath: "images/Marsh-Mallow.png" },
  { text: "Mast", tier: "Easy", imagePath: "images/Mast.png" },
  { text: "Master", tier: "Medium", imagePath: "images/Master.png" },
  { text: "Mature Lady", tier: "Easy", imagePath: "images/Mature Lady.png" },
  { text: "Merger", tier: "Easy", imagePath: "images/Merger.png" },
  { text: "Mermaid", tier: "Medium", imagePath: "images/Mermaid.png" },
  { text: "Mexican Style", tier: "Easy", imagePath: "images/Mexican Style.png" },
  { text: "Midnight", tier: "Hard", imagePath: "images/Midnight.png" },
  { text: "Military Style", tier: "Hard", imagePath: "images/Military Style.png" },
  { text: "Milk Chocolate", tier: "Medium", imagePath: "images/Milk Chocolate.png" },
  { text: "Mirrage", tier: "Easy", imagePath: "images/Mirrage.png" },
  { text: "Missionary", tier: "Easy", imagePath: "images/Missionary.png" },
  { text: "Moan", tier: "Easy", imagePath: "images/Moan.png" },
  { text: "Moonlight", tier: "Medium", imagePath: "images/Moonlight.png" },
  { text: "Multiply Pleasure", tier: "Medium", imagePath: "images/Multiply Pleasure.png" },
  { text: "Narcissus", tier: "Extreme", imagePath: "images/Narcissus.png" },
  { text: "Nasty Desire", tier: "Easy", imagePath: "images/Nasty Desire.png" },
  { text: "Necktie", tier: "Hard", imagePath: "images/Necktie.png" },
  { text: "Need For Speed", tier: "Medium", imagePath: "images/Need For Speed.png" },
  { text: "Nice Talk", tier: "Medium", imagePath: "images/Nice Talk.png" },
  { text: "Night-Fly", tier: "Hard", imagePath: "images/Night-Fly.png" },
  { text: "Nirvana", tier: "Easy", imagePath: "images/Nirvana.png" },
  { text: "Nun", tier: "Medium", imagePath: "images/Nun.png" },
  { text: "Oasis", tier: "Hard", imagePath: "images/Oasis.png" },
  { text: "Oath", tier: "Medium", imagePath: "images/Oath.png" },
  { text: "Octopus", tier: "Medium", imagePath: "images/Octopus.png" },
  { text: "Olympus", tier: "Extreme", imagePath: "images/Olympus.png" },
  { text: "Orgasm Generator", tier: "Hard", imagePath: "images/Orgasm Generator.png" },
  { text: "Overpass", tier: "Extreme", imagePath: "images/Overpass.png" },
  { text: "Overturned", tier: "Medium", imagePath: "images/Overturned.png" },
  { text: "Pearl", tier: "Medium", imagePath: "images/Pearl.png" },
  { text: "Penguin", tier: "Medium", imagePath: "images/Penguin.png" },
  { text: "Pie In The Sky", tier: "Easy", imagePath: "images/Pie In The Sky.png" },
  { text: "Piledriver", tier: "Medium", imagePath: "images/Piledriver.png" },
  { text: "Pioneer", tier: "Extreme", imagePath: "images/Pioneer.png" },
  { text: "Pisces 2", tier: "Medium", imagePath: "images/Pisces 2.png" },
  { text: "Pisces", tier: "Hard", imagePath: "images/Pisces.png" },
  { text: "Plain", tier: "Easy", imagePath: "images/Plain.png" },
  { text: "Plank", tier: "Easy", imagePath: "images/Plank.png" },
  { text: "Pleasure Bible", tier: "Hard", imagePath: "images/Pleasure Bible.png" },
  { text: "Plumber Position(1)", tier: "Easy", imagePath: "images/Plumber Position(1).png" },
  { text: "Plumber", tier: "Medium", imagePath: "images/Plumber.png" },
  { text: "Pointer", tier: "Medium", imagePath: "images/Pointer.png" },
  { text: "Pokemon", tier: "Hard", imagePath: "images/Pokemon.png" },
  { text: "Praying Mantis", tier: "Extreme", imagePath: "images/Praying Mantis.png" },
  { text: "Precipice", tier: "Medium", imagePath: "images/Precipice.png" },
  { text: "Pretzel Dip", tier: "Medium", imagePath: "images/Pretzel Dip.png" },
  { text: "Princess", tier: "Easy", imagePath: "images/Princess.png" },
  { text: "Prison Guard", tier: "Hard", imagePath: "images/Prison Guard.png" },
  { text: "Prone Bone", tier: "Easy", imagePath: "images/Prone Bone.png" },
  { text: "Propeller", tier: "Medium", imagePath: "images/Propeller.png" },
  { text: "Pterodactyl", tier: "Medium", imagePath: "images/Pterodactyl.png" },
  { text: "Punishment", tier: "Medium", imagePath: "images/Punishment.png" },
  { text: "Pussy Licking", tier: "Easy", imagePath: "images/Pussy Licking.png" },
  { text: "Puzzle", tier: "Medium", imagePath: "images/Puzzle.png" },
  { text: "Python", tier: "Hard", imagePath: "images/Python.png" },
  { text: "Rabbit Ears", tier: "Medium", imagePath: "images/Rabbit Ears.png" },
  { text: "Rainbow", tier: "Medium", imagePath: "images/Rainbow.png" },
  { text: "Rear Admiral", tier: "Medium", imagePath: "images/Rear Admiral.png" },
  { text: "Recharge", tier: "Easy", imagePath: "images/Recharge.png" },
  { text: "Reflection", tier: "Medium", imagePath: "images/Reflection.png" },
  { text: "Relaxation", tier: "Medium", imagePath: "images/Relaxation.png" },
  { text: "Revelation", tier: "Medium", imagePath: "images/Revelation.png" },
  { text: "Reverse Cowgirl", tier: "Easy", imagePath: "images/Reverse Cowgirl.png" },
  { text: "Ribbon", tier: "Medium", imagePath: "images/Ribbon.png" },
  { text: "Rider", tier: "Hard", imagePath: "images/Rider.png" },
  { text: "Riverside", tier: "Easy", imagePath: "images/Riverside.png" },
  { text: "Rock And Roll", tier: "Medium", imagePath: "images/Rock And Roll.png" },
  { text: "Rocket", tier: "Medium", imagePath: "images/Rocket.png" },
  { text: "Rocking Chair", tier: "Hard", imagePath: "images/Rocking Chair.png" },
  { text: "Rodeo", tier: "Medium", imagePath: "images/Rodeo.png" },
  { text: "Rose", tier: "Medium", imagePath: "images/Rose.png" },
  { text: "Saggitarius", tier: "Medium", imagePath: "images/Saggitarius.png" },
  { text: "Scissor", tier: "Medium", imagePath: "images/Scissor.png" },
  { text: "Scorpio", tier: "Easy", imagePath: "images/Scorpio.png" },
  { text: "Scorpion", tier: "Hard", imagePath: "images/Scorpion.png" },
  { text: "Screw", tier: "Medium", imagePath: "images/Screw.png" },
  { text: "Screwdriver", tier: "Hard", imagePath: "images/Screwdriver.png" },
  { text: "Seashell", tier: "Medium", imagePath: "images/Seashell.png" },
  { text: "Seesaw", tier: "Hard", imagePath: "images/Seesaw.png" },
  { text: "Sensual Touch", tier: "Medium", imagePath: "images/Sensual Touch.png" },
  { text: "Sevret Entrance", tier: "Medium", imagePath: "images/Sevret Entrance.png" },
  { text: "Sex Slave", tier: "Easy", imagePath: "images/Sex Slave.png" },
  { text: "She-Wolf", tier: "Medium", imagePath: "images/She-Wolf.png" },
  { text: "Shell", tier: "Easy", imagePath: "images/Shell.png" },
  { text: "Shining", tier: "Easy", imagePath: "images/Shining.png" },
  { text: "Shocker", tier: "Medium", imagePath: "images/Shocker.png" },
  { text: "Shuttle", tier: "Easy", imagePath: "images/Shuttle.png" },
  { text: "Shy Girl", tier: "Medium", imagePath: "images/Shy Girl.png" },
  { text: "Side Saddle", tier: "Medium", imagePath: "images/Side Saddle.png" },
  { text: "Silence", tier: "Medium", imagePath: "images/Silence.png" },
  { text: "Sixty-Nine On A Chair", tier: "Hard", imagePath: "images/Sixty-Nine On A Chair.png" },
  { text: "Sixty-Nine", tier: "Easy", imagePath: "images/Sixty-Nine.png" },
  { text: "Sledge", tier: "Medium", imagePath: "images/Sledge.png" },
  { text: "Sleeping Beauty", tier: "Medium", imagePath: "images/Sleeping Beauty.png" },
  { text: "Slide", tier: "Extreme", imagePath: "images/Slide.png" },
  { text: "Slope 2", tier: "Medium", imagePath: "images/Slope 2.png" },
  { text: "Slope", tier: "Medium", imagePath: "images/Slope.png" },
  { text: "Slow Dance", tier: "Easy", imagePath: "images/Slow Dance.png" },
  { text: "Snack", tier: "Hard", imagePath: "images/Snack.png" },
  { text: "Snail", tier: "Easy", imagePath: "images/Snail.png" },
  { text: "Snake Charmer", tier: "Easy", imagePath: "images/Snake Charmer.png" },
  { text: "Snow Angel", tier: "Extreme", imagePath: "images/Snow Angel.png" },
  { text: "Soft Chair", tier: "Hard", imagePath: "images/Soft Chair.png" },
  { text: "Soft Landing", tier: "Hard", imagePath: "images/Soft Landing.png" },
  { text: "Soldier", tier: "Easy", imagePath: "images/Soldier.png" },
  { text: "Source", tier: "Easy", imagePath: "images/Source.png" },
  { text: "Spanish Guitar", tier: "Medium", imagePath: "images/Spanish Guitar.png" },
  { text: "Spanish Sunset", tier: "Hard", imagePath: "images/Spanish Sunset.png" },
  { text: "Spark", tier: "Extreme", imagePath: "images/Spark.png" },
  { text: "Speaker", tier: "Medium", imagePath: "images/Speaker.png" },
  { text: "Special Breakfast", tier: "Medium", imagePath: "images/Special Breakfast.png" },
  { text: "Special Felatio", tier: "Easy", imagePath: "images/Special Felatio.png" },
  { text: "Speedbump", tier: "Easy", imagePath: "images/Speedbump.png" },
  { text: "Spicy Dish", tier: "Medium", imagePath: "images/Spicy Dish.png" },
  { text: "Spider", tier: "Hard", imagePath: "images/Spider.png" },
  { text: "Spiderman 2", tier: "Medium", imagePath: "images/Spiderman 2.png" },
  { text: "Spinhx", tier: "Easy", imagePath: "images/Spinhx.png" },
  { text: "Splitting Bamboo", tier: "Medium", imagePath: "images/Splitting Bamboo.png" },
  { text: "Spoon", tier: "Easy", imagePath: "images/Spoon.png" },
  { text: "Spork", tier: "Easy", imagePath: "images/Spork.png" },
  { text: "Spread Eagle", tier: "Medium", imagePath: "images/Spread Eagle.png" },
  { text: "Spring", tier: "Medium", imagePath: "images/Spring.png" },
  { text: "Sprout", tier: "Medium", imagePath: "images/Sprout.png" },
  { text: "Starfish", tier: "Hard", imagePath: "images/Starfish.png" },
  { text: "Stickman", tier: "Medium", imagePath: "images/Stickman.png" },
  { text: "Straddle", tier: "Easy", imagePath: "images/Straddle.png" },
  { text: "Straight Line", tier: "Medium", imagePath: "images/Straight Line.png" },
  { text: "Stuntman", tier: "Hard", imagePath: "images/Stuntman.png" },
  { text: "Submissive", tier: "Medium", imagePath: "images/Submissive.png" },
  { text: "Sucker Punch", tier: "Hard", imagePath: "images/Sucker Punch.png" },
  { text: "Superhero", tier: "Medium", imagePath: "images/Superhero.png" },
  { text: "Supernova", tier: "Medium", imagePath: "images/Supernova.png" },
  { text: "Superwoman", tier: "Hard", imagePath: "images/Superwoman.png" },
  { text: "Surf Board", tier: "Hard", imagePath: "images/Surf Board.png" },
  { text: "Sweet Pussy", tier: "Medium", imagePath: "images/Sweet Pussy.png" },
  { text: "Sweet Sin", tier: "Medium", imagePath: "images/Sweet Sin.png" },
  { text: "Swing 2", tier: "Extreme", imagePath: "images/Swing 2.png" },
  { text: "Swing", tier: "Hard", imagePath: "images/Swing.png" },
  { text: "Symphony", tier: "Easy", imagePath: "images/Symphony.png" },
  { text: "T Square", tier: "Medium", imagePath: "images/T Square.png" },
  { text: "Tamer", tier: "Medium", imagePath: "images/Tamer.png" },
  { text: "Tango", tier: "Medium", imagePath: "images/Tango.png" },
  { text: "Tantra Chair", tier: "Easy", imagePath: "images/Tantra Chair.png" },
  { text: "Tantric Cosmos", tier: "Hard", imagePath: "images/Tantric Cosmos.png" },
  { text: "Taurus", tier: "Hard", imagePath: "images/Taurus.png" },
  { text: "Temptation", tier: "Easy", imagePath: "images/Temptation.png" },
  { text: "Thirst", tier: "Easy", imagePath: "images/Thirst.png" },
  { text: "Thor’s Hammer", tier: "Hard", imagePath: "images/Thor’s Hammer.png" },
  { text: "Throat Swab", tier: "Medium", imagePath: "images/Throat Swab.png" },
  { text: "Tiara", tier: "Medium", imagePath: "images/Tiara.png" },
  { text: "Tight Squeeze", tier: "Medium", imagePath: "images/Tight Squeeze.png" },
  { text: "Tight Vagina", tier: "Hard", imagePath: "images/Tight Vagina.png" },
  { text: "Tiramisu", tier: "Easy", imagePath: "images/Tiramisu.png" },
  { text: "Titanic 2 Position(1)", tier: "Hard", imagePath: "images/Titanic 2 Position(1).png" },
  { text: "Titanic 2", tier: "Medium", imagePath: "images/Titanic 2.png" },
  { text: "Torch", tier: "Hard", imagePath: "images/Torch.png" },
  { text: "Tornado", tier: "Hard", imagePath: "images/Tornado.png" },
  { text: "Train", tier: "Easy", imagePath: "images/Train.png" },
  { text: "Triceratops", tier: "Hard", imagePath: "images/Triceratops.png" },
  { text: "Truck", tier: "Medium", imagePath: "images/Truck.png" },
  { text: "Tug Of War", tier: "Hard", imagePath: "images/Tug Of War.png" },
  { text: "Tugboat", tier: "Hard", imagePath: "images/Tugboat.png" },
  { text: "Tulip 2", tier: "Medium", imagePath: "images/Tulip 2.png" },
  { text: "Tulip", tier: "Easy", imagePath: "images/Tulip.png" },
  { text: "Turtle", tier: "Hard", imagePath: "images/Turtle.png" },
  { text: "Twerk On A Dick", tier: "Medium", imagePath: "images/Twerk On A Dick.png" },
  { text: "Twins", tier: "Hard", imagePath: "images/Twins.png" },
  { text: "Twix", tier: "Easy", imagePath: "images/Twix.png" },
  { text: "Unicorn", tier: "Easy", imagePath: "images/Unicorn.png" },
  { text: "V Formation", tier: "Hard", imagePath: "images/V Formation.png" },
  { text: "Valedictorian", tier: "Easy", imagePath: "images/Valedictorian.png" },
  { text: "Venus Flytrap", tier: "Easy", imagePath: "images/Venus Flytrap.png" },
  { text: "Venus", tier: "Medium", imagePath: "images/Venus.png" },
  { text: "Victory", tier: "Medium", imagePath: "images/Victory.png" },
  { text: "Virgo", tier: "Easy", imagePath: "images/Virgo.png" },
  { text: "Vulgar Chair", tier: "Hard", imagePath: "images/Vulgar Chair.png" },
  { text: "Wall", tier: "Medium", imagePath: "images/Wall.png" },
  { text: "Waterfall", tier: "Hard", imagePath: "images/Waterfall.png" },
  { text: "Watering Can", tier: "Easy", imagePath: "images/Watering Can.png" },
  { text: "Watermellon", tier: "Hard", imagePath: "images/Watermellon.png" },
  { text: "Wedge", tier: "Medium", imagePath: "images/Wedge.png" },
  { text: "Weightlessness", tier: "Extreme", imagePath: "images/Weightlessness.png" },
  { text: "Weird Fantasy", tier: "Medium", imagePath: "images/Weird Fantasy.png" },
  { text: "Wheelbarrow", tier: "Hard", imagePath: "images/Wheelbarrow.png" },
  { text: "Whisper", tier: "Easy", imagePath: "images/Whisper.png" },
  { text: "Wild Oga", tier: "Hard", imagePath: "images/Wild Oga.png" },
  { text: "Wild Pony", tier: "Medium", imagePath: "images/Wild Pony.png" },
  { text: "Woven Rose", tier: "Medium", imagePath: "images/Woven Rose.png" },
  { text: "XXX", tier: "Medium", imagePath: "images/XXX.png" },
  { text: "Yin-Yang", tier: "Medium", imagePath: "images/Yin-Yang.png" },
  { text: "Young Stalion", tier: "Medium", imagePath: "images/Young Stalion.png" },
  { text: "Zeal", tier: "Easy", imagePath: "images/Zeal.png" },
  { text: "Zeus", tier: "Easy", imagePath: "images/Zeus.png" },
  { text: "Zodiac", tier: "Medium", imagePath: "images/Zodiac.png" },
  { text: "Zombie", tier: "Medium", imagePath: "images/Zombie.png" },
];
